# Generated by Django 5.0.7 on 2024-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField(max_length=30)),
                ('temperature_2m_max', models.FloatField()),
                ('temperature_2m_min', models.FloatField()),
                ('precipitation_hours', models.FloatField()),
                ('precipitation_probability_max', models.FloatField()),
                ('wind_speed_10m_max', models.FloatField()),
                ('wind_gusts_10m_max', models.FloatField()),
                ('wind_direction_10m_dominant', models.FloatField()),
            ],
        ),
    ]
