# Generated by Django 5.0.7 on 2024-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecastapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastmodel',
            name='city_name',
            field=models.CharField(max_length=30),
        ),
    ]
